### ISSUE TITLE
ssl connection failed

### ISSUE THREAD

**Issue by xianzhaowang** [eidheim/Simple-WebSocket-Server#64]
Just follow the steps, but once I did ssl connection, it crashed, which stack is as bellow. anything wrong with my settings. Tried different browser no help.

 python SimpleExampleServer.py --example chat --ssl 1 --cert ./cert.pem 
Traceback (most recent call last):
  File "SimpleExampleServer.py", line 71, in <module>
    server.serveforever()
  File "/root/kw/wss/SimpleWebSocketServer.py", line 696, in serveforever
    super(SimpleSSLWebSocketServer, self).serveforever()
  File "/root/kw/wss/SimpleWebSocketServer.py", line 654, in serveforever
    client.handleClose()
  File "SimpleExampleServer.py", line 38, in handleClose
    clients.remove(self)
ValueError: list.remove(x): x not in list

**Comment by eidheim** [comment]
You sure you posted this issue on the right github repository;)? This repository is a C++ library.
